#Kubernetes app deployment yaml file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}
spec:
  selector:
    matchLabels:
      app: {{APP_NAME}}
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    tempate: 
      metadata:
        labels:
          app: {{APP_NAME}}
      spec:
        containers:
          - name: {{APP_NAME}}
            image: {{IMAGE_URL}}
            ports:
            - containerPort: 8080